#!/bin/sh

yum -y update
yum -y install unzip wget curl cloud-init git


#### UGLY, UGLY hack
#### I implemented the UpCLoud cloud-init support by myself and haven't pushed it 
#### back to the main repo, neither do I want to create my own cloud-init distribution...

git clone https://github.com/mkaesz/cloud-init.git

cd cloud-init

cp cloudinit/sources/DataSourceUpCloud.py /usr/lib/python3.6/site-packages/cloudinit/sources
cp cloudinit/sources/helpers/upcloud.py /usr/lib/python3.6/site-packages/cloudinit/sources/helpers
cp cloudinit/apport.py /usr/lib/python3.6/site-packages/cloudinit/apport.py
cp cloudinit/settings.py /usr/lib/python3.6/site-packages/cloudinit/settings.py

cd..

rm -rf cloud-init

cat > /etc/cloud/cloud.cfg.d/99-warnings.cfg << EOF
#cloud-config                                                          
datasource_list: [ UpCloud, None ]
datasource:
 UpCloud:
warnings:                                                             
  dsid_missing_source: off
EOF

systemctl enable cloud-init-local.service
systemctl enable cloud-init.service
systemctl enable cloud-config.service
systemctl enable cloud-final.service
