#!/bin/sh

yum -y update
yum -y install unzip wget curl cloud-init git

git clone git@github.com:mkaesz/cloud-init.git

cd cloud-init

cp cloud-init/sources/DataSourceUpCloud.py /usr/lib/python3.6/site-packages/cloudinit/sources
cp cloud-init/sources/helpers/upcloud.py /usr/lib/python3.6/site-packages/cloudinit/sources/helpers
cp cloud-init/apport.py /usr/lib/python3.6/site-packages/cloudinit/apport.py
cp cloud-init/setting.py /usr/lib/python3.6/site-packages/cloudinit/setting.py

