#!/bin/sh

#yum -y update
yum -y install unzip wget curl cloud-init git

git clone https://github.com/mkaesz/cloud-init.git

cd cloud-init

cp cloudinit/sources/DataSourceUpCloud.py /usr/lib/python3.6/site-packages/cloudinit/sources
cp cloudinit/sources/helpers/upcloud.py /usr/lib/python3.6/site-packages/cloudinit/sources/helpers
cp cloudinit/apport.py /usr/lib/python3.6/site-packages/cloudinit/apport.py
cp cloudinit/settings.py /usr/lib/python3.6/site-packages/cloudinit/settings.py

systemctl enable cloud-init-local.service
systemctl start cloud-init-local.service

systemctl enable cloud-init.service
systemctl start cloud-init.service

systemctl enable cloud-config.service
systemctl start cloud-config.service

systemctl enable cloud-final.service
systemctl start cloud-final.service
