name: Packer Docker image

on:
  push:

jobs:
  build_image:
    name: Build Packer image with Upcloud plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v4
        name: Build & push Docker image
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          image: packer-builds/packer
          githubOrg: servicecontrol

