---

name: Packer GitHub Actions
author: Kerim Satirli <kerim@operatehappy.com>
description: Run Packer commands

inputs:
  image:
    description: container image to use
    required: true
    default: 'Dockerfile'
  command:
    description: command to execute
    required: true
  arguments:
    description: arguments for command
  target:
    description: file(s) to target
    required: true
    default: build.json
  repo-token:
    description: Github token to authenticate to Github packages
    required: false

outputs:
  command:
    description: interpolated command (incl. arguments) that will be executed

runs:
  using: 'docker'
  image: 'ghcr.io/servicecontrol/packer-builds/packer:latest'
  #  image: ${{ inputs.image }}
 
branding:
  color: blue
  icon: package
